### ISSUE TITLE
En el repositorio solo debe almacenarse código fuente

### ISSUE THREAD

**Issue by evolentini** [m-scasserra/TP2TSSE#1]
En el repositorio no se debe almacenar ni código binario ni archivos generados por herramientas automáticas, solo se debe almacenar código fuente. Por eso la carpeta `build` debe agregarse en el archivo `.gitignore` y eliminarse de repositorio.

@marianofino @rafaeloliva

**Comment by m-scasserra** [comment]
Arreglado en el commit [3833716](https://github.com/m-scasserra/TP2TSSE/commit/383371667a8e52f9716f098864c8422325774f95)
