### ISSUE TITLE
Se debe refactorizar el código de producción para eliminar repeticiones

### ISSUE THREAD

**Issue by evolentini** [m-scasserra/TP2TSSE#2]
En esta línea 

https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/src/leds.c#L20

se debería llamar a la función `ledsTurnOffAll()` en lugar de repetir la asignación de valores a la variable. Aun cuando es muy poco código es una buena practica evitar repeticiones. En este caso incluso el requisito dice que los leds deben arrancar apagados, por lo que es totalmente lógico llamar a la función para apagar todos.

@marianofino @rafaeloliva

**Comment by m-scasserra** [comment]
Arreglado en el commit [3833716](https://github.com/m-scasserra/TP2TSSE/commit/383371667a8e52f9716f098864c8422325774f95)
