### ISSUE TITLE
No es necesario prender y apagar un led para saber que esta apagado

### ISSUE THREAD

**Issue by evolentini** [m-scasserra/TP2TSSE#3]
Estas dos lineas se pueden eliminar

https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L61-L62

ya hay un test anterior que garantiza que todos los leds arrancan apagados, no es necesario prender y apagar el led para consultar el estado de un led apagado. Lo mismo ocurre con estas otras dos lineas

https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L81-L82

@marianofino @rafaeloliva

**Comment by m-scasserra** [comment]
Arreglado en el commit [3833716](https://github.com/m-scasserra/TP2TSSE/commit/383371667a8e52f9716f098864c8422325774f95)
