### ISSUE TITLE
Se pueden refactorizar las pruebas para escribir menos (y hacerlas mas declarativas)

### ISSUE THREAD

**Issue by evolentini** [m-scasserra/TP2TSSE#4]
Se puede usar un `TEST_ASSERT()` directamente sobre el resultado de la función para evitar declarar la variable. De esta forma estas pruebas quedarían mas compactas.

https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L53-L55
https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L63-L65
https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L73-L75
https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L84-L86

@marianofino @rafaeloliva

**Comment by m-scasserra** [comment]
Arreglado en el commit [3833716](https://github.com/m-scasserra/TP2TSSE/commit/383371667a8e52f9716f098864c8422325774f95)
