### ISSUE TITLE
No se debe dejar código comentado en producción

### ISSUE THREAD

**Issue by evolentini** [m-scasserra/TP2TSSE#5]
El código que no se utiliza debería ser removido antes de enviarlo a producción.

https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L19-L20

https://github.com/m-scasserra/TP2TSSE/blob/5421f581e341529567415a26da203d142804f4c6/test/test_leds.c#L83

@marianofino @rafaeloliva

**Comment by m-scasserra** [comment]
Arreglado en el commit [3833716](https://github.com/m-scasserra/TP2TSSE/commit/383371667a8e52f9716f098864c8422325774f95)
